### PR TITLE
Feat support win64 (vcpkg+CMake) for rocksdb

### PR DESCRIPTION
**Pull request by kabu1204**
YCSB-cpp can now be built on windows, using vcpkg and CMake.
See README.md for usage.

### CODE REVIEW

**Comment by kabu1204** [comment]
The PR is not intended to merge into this repo. Sorry for the missing. I'll close the PR.

**Comment by ls4154** [comment]
Looks great. :)

**Comment by kabu1204** [comment]
> Looks great. :)

Thanks.
There's a strange problem. I've just tested with recordcount=100M and threadcount=8 on windows, the `StatusThread` may randomly exit early(`done=true`), even though all `ClientThread`s are still running (the `latch->count_` is still 8). The exiting timing varies, maybe at 9s, 30s or several minutes. The `ClientThread`s will keep running to the end normally.

Yes, I observed `9 sec` while the interval is set to 10s. I've not encountered this situation on Linux before, which makes me doubt the precision and resolution of `std::chrono` on windows.

I tried this change:
```cpp
// countdown_latch.h:26
return cv_.wait_for(lock, std::chrono::seconds(timeout_sec), [this]{return count_ <= 0;});
// return cv_.wait_for(lock, std::chrono::seconds(timeout_sec)) == std::cv_status::no_timeout;
```
I run the test another 5 times and the problem didn't appear. I cannot explain why.

Is this a coincide? Am I missing something?

**Comment by ls4154** [comment]
CV is notified only when all ClientThread are terminated, so I think StatusThread should not wake up for reason other than timeout. Still, it might be safe to check the count after wake up.

**Comment by kabu1204** [comment]
> CV is notified only when all ClientThread are terminated, so I think StatusThread should not wake up for reason other than timeout. Still, it might be safe to check the count after wake up.

You're right. We need to check the count on windows.
After a boring search, I found the reason:
https://devblogs.microsoft.com/oldnewthing/20180201-00/?p=97946

and from [cplusplus/wait_for](https://cplusplus.com/reference/condition_variable/condition_variable/wait_for/) :
> Generally, the function is notified to wake up by a call in another thread either to member [notify_one](https://cplusplus.com/condition_variable::notify_one) or to member [notify_all](https://cplusplus.com/condition_variable::notify_all). But certain implementations may produce spurious wake-up calls without any of these functions being called. Therefore, users of this function shall ensure their condition for resumption is met.
> 
> If pred is specified (2), the function only blocks if pred returns false, and notifications can only unblock the thread when it becomes true (which is especially useful to check against spurious wake-up calls).

**Comment by ls4154** [comment]
Thanks! I didn't know that since I've never tested it in a Windows environment. I'll fix it soon, or please feel free to submit PR.

**Comment by kabu1204** [comment]
> Thanks! I didn't know that since I've never tested it in a Windows environment. I'll fix it soon, or please feel free to submit PR.

OK. I've run heavy tests(1G record count and 100M opcount) with rocksdb on windows all day today. It seems there's no problem.
I plan to add support for wiredtiger on windows, along with lmdb and leveldb, before making a PR to this repo.

**Pull request closed without merging**
